In [1]:
import numpy as np

In [2]:
arr1 = np.arange(6).reshape(2,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
arr2 = np.arange(6,12).reshape(2,3)

In [5]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
arr1 * arr2 # arr1 ning elementlarini arr2 ning elementlariga ko'paytiradi

array([[ 0,  7, 16],
       [27, 40, 55]])

In [7]:
arr2 / arr1 # arr2 ning elementlarini arr1 ning elementlariga bo'ladi

/var/folders/25/5675xj_52zl9fc8n01wb0l6h0000gn/T/ipykernel_6285/1818724351.py:1: RuntimeWarning: divide by zero encountered in divide
  arr2 / arr1 # arr2 ning elementlarini arr1 ning elementlariga bo'ladi


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [8]:
arr1 + arr2 #arr1 ning elementlarini arr2 ning elementlariga qo'shadi

array([[ 6,  8, 10],
       [12, 14, 16]])

In [9]:
arr2 - arr1 #arr1 ning elementlaridan arr1 ning elementlarini ayiradi

array([[6, 6, 6],
       [6, 6, 6]])

In [10]:
arr1 **2 # arr1 ning elementlarini kvadratga oshirish

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [11]:
arr2 **0.5 # arr2 ning elementlarini kvadrat ildizini hisoblaydi

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])