In [1]:
import numpy as np

In [3]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [6]:
a.reshape(3,2) #massiv shaklini o'zgartirish

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
a.T # a massivning Transpose ko'rinishi

array([[0, 2, 4],
       [1, 3, 5]])

In [9]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [12]:
a.swapaxes(1,0) # a massivni swaping axes usulida Transpose ko'rinishi

array([[0, 2, 4],
       [1, 3, 5]])

In [14]:
np.dot(a, a.T) # bir turdagi massivni boshqa turdagi massivga ko'paytirish

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])