In [1]:
import numpy as np

In [8]:
ismlar = np.array(["Ali", "Vali", "Salim", "Kamol", "Jamol", "Salim", "Vali"])

In [9]:
data = np.random.randn(7,4) #ismlarga mos ravishda (7,4) o'lchamli massiv

In [12]:
ismlar

array(['Ali', 'Vali', 'Salim', 'Kamol', 'Jamol', 'Salim', 'Vali'],
      dtype='<U5')

In [13]:
data

array([[-1.03035643,  0.48574385, -0.74949739, -0.90004501],
       [-0.41346459,  0.05494531, -1.22783449,  1.27707124],
       [ 1.68874053,  0.18414869,  1.22486952,  0.32503884],
       [-0.9168205 , -2.27937401,  1.11908505, -1.25027803],
       [-1.50503279,  0.11712327,  0.47834472,  0.88487657],
       [ 0.68192423,  0.30601515, -0.55976379, -1.31535587],
       [-0.17602517,  0.67529594, -0.26213684,  0.25450572]])

In [17]:
ismlar == "Vali" #Boolean qiymat qaytaradi

array([False,  True, False, False, False, False,  True])

In [18]:
data[ismlar == "Vali"] #Valiga tegishli barcha malumotlarni kesib olish

array([[-0.41346459,  0.05494531, -1.22783449,  1.27707124],
       [-0.17602517,  0.67529594, -0.26213684,  0.25450572]])

In [19]:
data[ismlar == "Jamol"]

array([[-1.50503279,  0.11712327,  0.47834472,  0.88487657]])

In [29]:
data[ismlar == "Vali", 2:] #Valiga tegishli 2-ustundan keyingi barcha elementlar

array([[-1.22783449,  1.27707124],
       [-0.26213684,  0.25450572]])

In [31]:
data[ismlar == "Vali", :2] #dastlabki ikta ustundagi barcha malumotlar

array([[-0.41346459,  0.05494531],
       [-0.17602517,  0.67529594]])

In [33]:
data[ismlar == "Vali", 1:3] #o'rtadagi ikta ustun malumotlari

array([[ 0.05494531, -1.22783449],
       [ 0.67529594, -0.26213684]])

In [35]:
data[ismlar != "Vali"] #Validan boshqa barchaning malumotlarini kesish

array([[-1.03035643,  0.48574385, -0.74949739, -0.90004501],
       [ 1.68874053,  0.18414869,  1.22486952,  0.32503884],
       [-0.9168205 , -2.27937401,  1.11908505, -1.25027803],
       [-1.50503279,  0.11712327,  0.47834472,  0.88487657],
       [ 0.68192423,  0.30601515, -0.55976379, -1.31535587]])

In [36]:
data[~(ismlar == "Vali")] #(~) teng emas belgisi

array([[-1.03035643,  0.48574385, -0.74949739, -0.90004501],
       [ 1.68874053,  0.18414869,  1.22486952,  0.32503884],
       [-0.9168205 , -2.27937401,  1.11908505, -1.25027803],
       [-1.50503279,  0.11712327,  0.47834472,  0.88487657],
       [ 0.68192423,  0.30601515, -0.55976379, -1.31535587]])

In [40]:
data[(ismlar == "Ali") | (ismlar == "Salim")] #Ali va Salimga tegishli malumotlarni kesish

array([[-1.03035643,  0.48574385, -0.74949739, -0.90004501],
       [ 1.68874053,  0.18414869,  1.22486952,  0.32503884],
       [ 0.68192423,  0.30601515, -0.55976379, -1.31535587]])

In [41]:
print(ismlar)
print(data)

['Ali' 'Vali' 'Salim' 'Kamol' 'Jamol' 'Salim' 'Vali']
[[-1.03035643  0.48574385 -0.74949739 -0.90004501]
 [-0.41346459  0.05494531 -1.22783449  1.27707124]
 [ 1.68874053  0.18414869  1.22486952  0.32503884]
 [-0.9168205  -2.27937401  1.11908505 -1.25027803]
 [-1.50503279  0.11712327  0.47834472  0.88487657]
 [ 0.68192423  0.30601515 -0.55976379 -1.31535587]
 [-0.17602517  0.67529594 -0.26213684  0.25450572]]


In [44]:
mask = (ismlar == "Vali") | (ismlar == "Jamol")

In [64]:
data[mask]

array([[0.        , 0.        , 0.        , 0.09142271],
       [1.35694767, 0.        , 0.        , 0.19263616],
       [0.60404196, 0.05352878, 0.47586266, 0.84684572]])

In [68]:
data[data<0] = 0

In [69]:
data

array([[0.        , 0.23476426, 0.        , 1.2892155 ],
       [0.        , 0.        , 0.        , 0.09142271],
       [0.07752669, 0.        , 0.        , 0.58120553],
       [0.        , 0.95955577, 0.99840858, 0.0448592 ],
       [1.35694767, 0.        , 0.        , 0.19263616],
       [1.95773003, 0.55618417, 2.73981763, 0.        ],
       [0.60404196, 0.05352878, 0.47586266, 0.84684572]])