In [1]:
import numpy as np

In [2]:
x = np.arange(6).reshape(2,3)

In [5]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
y = np.arange(6,12).reshape(3,2)

In [7]:
y

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [9]:
x.dot(y) #matritsalarni ko'paytirish

array([[ 28,  31],
       [100, 112]])

In [10]:
y.dot(x)

array([[21, 34, 47],
       [27, 44, 61],
       [33, 54, 75]])

In [12]:
np.dot(x, y) # x ni y ga ko'paytirish

array([[ 28,  31],
       [100, 112]])

In [14]:
np.dot(y, x) #y ni x ga ko'paytirish

array([[21, 34, 47],
       [27, 44, 61],
       [33, 54, 75]])