In [2]:
import numpy as np

In [3]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [4]:
np.save("data", arr) # massivni "data" nomi bilan saqlash

In [7]:
arr2 = np.load("data.npy") # saqlab qo'ygan massivni choqirish

In [8]:
arr2

array([0, 1, 2, 3, 4, 5])

In [9]:
arr3 = np.arange(20)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
np.savez("arrays", a = arr, b = arr3) #ikta massivni saqlash

In [12]:
arrays = np.load("arrays.npz")

In [13]:
arrays['a'] # a nom bilan saqlangan arr massivi

array([0, 1, 2, 3, 4, 5])

In [15]:
arrays['b'] #b nom bilan saqlangan arr3 massivi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])