In [1]:
import numpy as np

In [2]:
arr = np.arange(10, 100, 10) #10 dan boshlab 100gacha 10 qadam bilan

In [3]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
arr[0]

np.int64(10)

In [5]:
arr[-2]

np.int64(80)

In [7]:
arr[3:5] #3-indeksdan 5-indeksgacha bo'lgan qiymatlarni qaytaradi

array([40, 50])

In [8]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [9]:
sliced_arr = arr[3:5]

In [10]:
sliced_arr[:] = 0

In [11]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [12]:
arr1 = np.arange(10, 100, 10)

In [13]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
sliced_arr1 = arr1[3:5].copy()

In [17]:
sliced_arr1

array([40, 50])