In [1]:
import numpy as np

In [2]:
arr = np.arange(10, 100, 10) #10 dan boshlab 100gacha 10 qadam bilan

In [3]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
arr[0]

np.int64(10)

In [5]:
arr[-2]

np.int64(80)

In [7]:
arr[3:5] #3-indeksdan 5-indeksgacha bo'lgan qiymatlarni qaytaradi

array([40, 50])

In [8]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [9]:
sliced_arr = arr[3:5]

In [10]:
sliced_arr[:] = 0

In [11]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [12]:
arr1 = np.arange(10, 100, 10)

In [13]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
sliced_arr1 = arr1[3:5].copy() 

In [17]:
sliced_arr1

array([40, 50])

In [19]:
sliced_arr1[:] = 0
sliced_arr1

array([0, 0])

In [21]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
#2 o'lchamli massivni kesish

In [24]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]]) #(3,3) o'lchamli massiv

In [25]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr2d.ndim

2

In [28]:
arr2d[1,1] #1-qator 1-ustundagi element

np.int64(5)

In [30]:
arr2d[2,2] #2-qator 2-ustundagi element

np.int64(9)

In [31]:
sl_arr = arr2d[2, 1:] #2-qator 1-ustunda turgan elementdan 2-qator oxirgi elementigacha bo'lgan elementlarni qaytaradi

In [32]:
sl_arr

array([8, 9])

In [33]:
#3 o'lchamli massivlarni kesish

In [41]:
arr3d = np.array([[[0,1,2],[3,4,5],[6,7,8]],[[9,10,11],[12,13,14],[15,16,17]],[[18,19,20],[21,22,23],[24,25,26]]])

In [42]:
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [43]:
arr3d.ndim

3

In [53]:
arr3d[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
arr3d[0][1,1]

np.int64(4)

In [55]:
arr3d[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [57]:
arr3d[1][2,1:]

array([16, 17])

In [58]:
arr3d[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [63]:
arr3d[2][1,:2]

array([21, 22])