In [2]:
import numpy as np

In [3]:
#mantiqiy shart operatorlarini massiv operatori sifatida ishlatish

In [9]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [6]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [10]:
xarr

array([1.1, 1.2, 1.3, 1.4, 1.5])

In [11]:
yarr

array([2.1, 2.2, 2.3, 2.4, 2.5])

In [12]:
cond = np.array([True, False, True, True, False]) # agar element True bo'lsa xarr dan qiymat qabul qiladi, agar False bo'lsa yarr dan qiymat qabul qiladi

In [13]:
# where
result = np.where(cond, xarr, yarr) #agar element True bo'lsa xarr dan qiymat qabul qiladi, agar False bo'lsa yarr dan qiymat qabul qiladi

In [14]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [15]:
arr = np.random.randn(4,4) # 4ga 4 o'lchamli massiv

In [16]:
arr

array([[-1.5615803 ,  1.08779758,  0.86121912, -1.40831712],
       [ 0.67557962,  0.29044162,  0.51460355, -0.69809991],
       [-1.04747364, -0.30846635,  1.36607774, -0.52325639],
       [ 0.25018028,  0.4111663 , -0.96167177,  2.02789819]])

In [17]:
results = np.where(arr<0, -2, 2) # arr ning 0 dan kichkina qiymatlarini -2ga 0 dan katta qiymatlarini 2 ga tenglashtirib qo'yadi

In [18]:
results

array([[-2,  2,  2, -2],
       [ 2,  2,  2, -2],
       [-2, -2,  2, -2],
       [ 2,  2, -2,  2]])