In [1]:
import numpy as np

In [2]:
arr = np.random.randn(5,4)
arr

array([[ 0.22557848, -1.34206936, -0.64818915,  0.65880756],
       [ 0.54566195, -0.06245509, -1.34863814,  0.68824357],
       [-0.8294829 , -0.33748741,  0.80611072, -0.22452416],
       [ 1.41984076,  1.35922604,  0.06607047, -2.16689201],
       [ 0.77041977, -0.36358648,  1.3061048 , -0.40945872]])

In [3]:
np.sum(arr) # arr ning barcha elementlari yig'indisini hisoblash

np.float64(0.1132806939070451)

In [5]:
arr.sum() #yuqoridagi natija bilan bir xil

np.float64(0.1132806939070451)

In [7]:
arr = np.where(arr<0, -1,2)

In [8]:
arr

array([[ 2, -1, -1,  2],
       [ 2, -1, -1,  2],
       [-1, -1,  2, -1],
       [ 2,  2,  2, -1],
       [ 2, -1,  2, -1]])

In [19]:
np.sum(arr, axis = 1) # gorizantal chiziq bo'ylab elementlarni qo'shib qaytaradi

array([ 2,  2, -1,  5,  2])

In [20]:
np.sum(arr, axis = 0) # vertikal(ustun) chiziq bo'ylab elementlarni qo'shib qaytaradi

array([ 7, -2,  4,  1])

In [21]:
np.mean(arr) # arr elementlarining o'rta arifmryik qiymatini hisoblash

np.float64(0.5)

In [22]:
test = np.arange(5)
test

array([0, 1, 2, 3, 4])

In [23]:
np.sum(test)/len(test) # test massivining elementlarining o'rta arifmetigi

np.float64(2.0)

In [24]:
np.mean(test) # yuqoridagi bilan bir xil natija qaytaradi

np.float64(2.0)

In [25]:
arr

array([[ 2, -1, -1,  2],
       [ 2, -1, -1,  2],
       [-1, -1,  2, -1],
       [ 2,  2,  2, -1],
       [ 2, -1,  2, -1]])

In [26]:
np.mean(arr, axis = 1) # qator bo'yicha o'rtacha qiymat

array([ 0.5 ,  0.5 , -0.25,  1.25,  0.5 ])

In [28]:
np.mean(arr, axis = 0) # ustun bo'yicha o'rtacha qiymat 

array([ 1.4, -0.4,  0.8,  0.2])

In [29]:
#cumsum barcha yig'indilarni hisoblab boruvchi yig'indi

In [30]:
test

array([0, 1, 2, 3, 4])

In [32]:
data = np.cumsum(test) # har bir elementni o'sha elementgacha bo'lgan barcha qiymatlarni qo'shib yozadi

In [35]:
data # array([0, 0+1, 0+1+2, 0+1+2+3, 0+1+2+3+4 ]) ni qaytaradi

array([ 0,  1,  3,  6, 10])