In [1]:
import numpy as np

In [2]:
# numpy kutubxonasida massiv yaratish
data = [2, 4.5, 12, 8.3] #list
arr = np.array(data) #array

In [3]:
arr

array([ 2. ,  4.5, 12. ,  8.3])

In [4]:
data2 = (2, 3.4, 13, 5.8) #tuple
arr2 = np.array(data2)

In [5]:
arr2

array([ 2. ,  3.4, 13. ,  5.8])

In [6]:
print("test2")

test2


In [7]:
arr.ndim #arr ning o`lchami

1

In [8]:
arr2.ndim #arr2 ning o`lchami

1

In [9]:
print("test3")

test3


In [11]:
#Ikki va undan katta o`lchamli massivlar
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]] #nested list

In [12]:
arr3 = np.array(data3)

In [14]:
arr3 #Ikki o`lchamli massiv

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr3.ndim

2

In [17]:
#shape va size metodlari
arr3.shape #qator va ustunlar sonini ko`rsatadi (q, u)

(2, 4)

In [19]:
arr3.size #massiv ichidagi barcha elementlar sonini ko`rsatadi

8

In [20]:
#N o`lchamli massiv yaratishning zeros va ones usullari

In [23]:
arr4 = np.zeros(shape = (2, 4)) #barcha elementlari 0 ga teng (2, 4)

In [22]:
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
arr5 = np.zeros((3, 5))

In [25]:
arr5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
arr6 = np.ones((2,4)) #barcha elementlar 1 ga teng 2 qator 4 ustun

In [27]:
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
#arange funksiyasi yordamida massiv yaratish

In [30]:
arr7 = np.arange(4,20,2) # 4dan 20gacha 2 qadam bilan qiymatlarni massivga joylaydi

In [31]:
arr7

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
arr8 = np.arange(20) #0 dan 20gacha qiymatlarni 1 qadam bilan massivga joylaydi

In [33]:
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])