In [1]:
import numpy as np

In [6]:
arr = np.random.rand(4)

In [7]:
arr

array([0.74224907, 0.28256017, 0.71873921, 0.15705589])

In [15]:
np.sort(arr) #sonlarni kichigidan kattasiga qarab tartiblaydi

array([0.15705589, 0.28256017, 0.71873921, 0.74224907])

In [24]:
arr

array([0.15705589, 0.28256017, 0.71873921, 0.74224907])

In [27]:
rev_arr = -np.sort(-arr) # Katta qiymatda kichigiga qarab tartiblash

In [28]:
rev_arr

array([0.74224907, 0.71873921, 0.28256017, 0.15705589])

In [29]:
arr2d = np.random.randn(2,4) # ikki o'lchamli 2 qator 4 ustunli massiv

In [30]:
arr2d

array([[ 0.54762443,  1.0346322 , -0.03199453,  0.32730969],
       [-0.98174515, -0.54457853,  1.37111528, -1.43405178]])

In [33]:
col_srt = np.sort(arr2d, axis = 0) # ustun bo'yicha tartiblash

In [34]:
col_srt

array([[-0.98174515, -0.54457853, -0.03199453, -1.43405178],
       [ 0.54762443,  1.0346322 ,  1.37111528,  0.32730969]])

In [35]:
row_srt = np.sort(arr2d, axis = 1) # qator bo'yicha tartiblash

In [36]:
row_srt

array([[-0.03199453,  0.32730969,  0.54762443,  1.0346322 ],
       [-1.43405178, -0.98174515, -0.54457853,  1.37111528]])