In [1]:
import numpy as np

In [2]:
# Unary funksiyalar (bitta argument qabul qiluvchi funksiya)

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sqrt(arr) #arr nomli massivning barcha elementlaridan kvadrat ildiz qaytaradi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [6]:
np.square(arr) # har bir elementning kvadratini qaytaradi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
np.exp(arr) # barcha elementlarning eksponentini qaytaradi

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [10]:
np.log(arr[1:]) #  0-elementidan boshqa barcha elementlarning logarifmik qiymatini qaytaradi

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [15]:
arr1 = np.random.randn(6) # 6 ta elementdan iborat taxminiy qiymatlarga ega massiv

In [16]:
arr1

array([-0.86246197,  1.33648389,  0.41216796, -0.7020319 , -0.61471129,
       -1.29964395])

In [17]:
qoldiq, butun = np.modf(arr1) # har bir elementni butun va qoldiq qismga ajratadi

In [18]:
print(qoldiq)
print(butun)

[-0.86246197  0.33648389  0.41216796 -0.7020319  -0.61471129 -0.29964395]
[-0.  1.  0. -0. -0. -1.]


In [19]:
np.sign(arr1) # qiymatlarni -1 va 1 qiymatlarga ajratadi

array([-1.,  1.,  1., -1., -1., -1.])